--- 
- name: playbook that creates user
  become: true
  hosts: all
  name: "adding user in deployment server"
  tasks: 
    - 
      name: "adding users remotely"
      user: 
        name: james
        shell: /bin/bash
